# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Heckler.Adapters.Twilio.Model.AccountShortCode do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :account_sid,
    :api_version,
    :date_created,
    :date_updated,
    :friendly_name,
    :short_code,
    :sid,
    :sms_fallback_method,
    :sms_fallback_url,
    :sms_method,
    :sms_url,
    :uri
  ]

  @type t :: %__MODULE__{
    :account_sid => String.t | nil,
    :api_version => String.t | nil,
    :date_created => String.t | nil,
    :date_updated => String.t | nil,
    :friendly_name => String.t | nil,
    :short_code => String.t | nil,
    :sid => String.t | nil,
    :sms_fallback_method => String.t | nil,
    :sms_fallback_url => String.t | nil,
    :sms_method => String.t | nil,
    :sms_url => String.t | nil,
    :uri => String.t | nil
  }

  def decode(value) do
    value
  end
end

