# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Heckler.Adapters.Twilio.Model.AccountMessageMessageFeedback do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :account_sid,
    :message_sid,
    :outcome,
    :date_created,
    :date_updated,
    :uri
  ]

  @type t :: %__MODULE__{
    :account_sid => String.t | nil,
    :message_sid => String.t | nil,
    :outcome => Heckler.Adapters.Twilio.Model.MessageFeedbackEnumOutcome.t | nil,
    :date_created => String.t | nil,
    :date_updated => String.t | nil,
    :uri => String.t | nil
  }

  alias Heckler.Adapters.Twilio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:outcome, :struct, Heckler.Adapters.Twilio.Model.MessageFeedbackEnumOutcome)
  end
end

