# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Heckler.Adapters.Twilio.Model.AccountAvailablePhoneNumberCountry do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :country_code,
    :country,
    :uri,
    :beta,
    :subresource_uris
  ]

  @type t :: %__MODULE__{
          :country_code => String.t() | nil,
          :country => String.t() | nil,
          :uri => String.t() | nil,
          :beta => boolean() | nil,
          :subresource_uris => map() | nil
        }

  def decode(value) do
    value
  end
end
