# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Heckler.Adapters.Twilio.Model.AccountConference do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :account_sid,
    :date_created,
    :date_updated,
    :api_version,
    :friendly_name,
    :region,
    :sid,
    :status,
    :uri,
    :subresource_uris,
    :reason_conference_ended,
    :call_sid_ending_conference
  ]

  @type t :: %__MODULE__{
    :account_sid => String.t | nil,
    :date_created => String.t | nil,
    :date_updated => String.t | nil,
    :api_version => String.t | nil,
    :friendly_name => String.t | nil,
    :region => String.t | nil,
    :sid => String.t | nil,
    :status => Heckler.Adapters.Twilio.Model.ConferenceEnumStatus.t | nil,
    :uri => String.t | nil,
    :subresource_uris => map() | nil,
    :reason_conference_ended => Heckler.Adapters.Twilio.Model.ConferenceEnumReasonConferenceEnded.t | nil,
    :call_sid_ending_conference => String.t | nil
  }

  alias Heckler.Adapters.Twilio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:status, :struct, Heckler.Adapters.Twilio.Model.ConferenceEnumStatus)
     |> Deserializer.deserialize(:reason_conference_ended, :struct, Heckler.Adapters.Twilio.Model.ConferenceEnumReasonConferenceEnded)
  end
end

