# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Heckler.Adapters.Twilio.Model.AccountConnectApp do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :account_sid,
    :authorize_redirect_url,
    :company_name,
    :deauthorize_callback_method,
    :deauthorize_callback_url,
    :description,
    :friendly_name,
    :homepage_url,
    :permissions,
    :sid,
    :uri
  ]

  @type t :: %__MODULE__{
          :account_sid => String.t() | nil,
          :authorize_redirect_url => String.t() | nil,
          :company_name => String.t() | nil,
          :deauthorize_callback_method => String.t() | nil,
          :deauthorize_callback_url => String.t() | nil,
          :description => String.t() | nil,
          :friendly_name => String.t() | nil,
          :homepage_url => String.t() | nil,
          :permissions => [Heckler.Adapters.Twilio.Model.ConnectAppEnumPermission.t()] | nil,
          :sid => String.t() | nil,
          :uri => String.t() | nil
        }

  alias Heckler.Adapters.Twilio.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :permissions,
      :list,
      Heckler.Adapters.Twilio.Model.ConnectAppEnumPermission
    )
  end
end
