# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Heckler.Adapters.Twilio.Model.AccountAddress do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :account_sid,
    :city,
    :customer_name,
    :date_created,
    :date_updated,
    :friendly_name,
    :iso_country,
    :postal_code,
    :region,
    :sid,
    :street,
    :uri,
    :emergency_enabled,
    :validated,
    :verified,
    :street_secondary
  ]

  @type t :: %__MODULE__{
    :account_sid => String.t | nil,
    :city => String.t | nil,
    :customer_name => String.t | nil,
    :date_created => String.t | nil,
    :date_updated => String.t | nil,
    :friendly_name => String.t | nil,
    :iso_country => String.t | nil,
    :postal_code => String.t | nil,
    :region => String.t | nil,
    :sid => String.t | nil,
    :street => String.t | nil,
    :uri => String.t | nil,
    :emergency_enabled => boolean() | nil,
    :validated => boolean() | nil,
    :verified => boolean() | nil,
    :street_secondary => String.t | nil
  }

  def decode(value) do
    value
  end
end

