# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Heckler.Adapters.Twilio.Model.AccountApplication do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :account_sid,
    :api_version,
    :date_created,
    :date_updated,
    :friendly_name,
    :message_status_callback,
    :sid,
    :sms_fallback_method,
    :sms_fallback_url,
    :sms_method,
    :sms_status_callback,
    :sms_url,
    :status_callback,
    :status_callback_method,
    :uri,
    :voice_caller_id_lookup,
    :voice_fallback_method,
    :voice_fallback_url,
    :voice_method,
    :voice_url,
    :public_application_connect_enabled
  ]

  @type t :: %__MODULE__{
    :account_sid => String.t | nil,
    :api_version => String.t | nil,
    :date_created => String.t | nil,
    :date_updated => String.t | nil,
    :friendly_name => String.t | nil,
    :message_status_callback => String.t | nil,
    :sid => String.t | nil,
    :sms_fallback_method => String.t | nil,
    :sms_fallback_url => String.t | nil,
    :sms_method => String.t | nil,
    :sms_status_callback => String.t | nil,
    :sms_url => String.t | nil,
    :status_callback => String.t | nil,
    :status_callback_method => String.t | nil,
    :uri => String.t | nil,
    :voice_caller_id_lookup => boolean() | nil,
    :voice_fallback_method => String.t | nil,
    :voice_fallback_url => String.t | nil,
    :voice_method => String.t | nil,
    :voice_url => String.t | nil,
    :public_application_connect_enabled => boolean() | nil
  }

  def decode(value) do
    value
  end
end

