# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Heckler.Adapters.Twilio.Model.AccountNotification do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :account_sid,
    :api_version,
    :call_sid,
    :date_created,
    :date_updated,
    :error_code,
    :log,
    :message_date,
    :message_text,
    :more_info,
    :request_method,
    :request_url,
    :sid,
    :uri
  ]

  @type t :: %__MODULE__{
          :account_sid => String.t() | nil,
          :api_version => String.t() | nil,
          :call_sid => String.t() | nil,
          :date_created => String.t() | nil,
          :date_updated => String.t() | nil,
          :error_code => String.t() | nil,
          :log => String.t() | nil,
          :message_date => String.t() | nil,
          :message_text => String.t() | nil,
          :more_info => String.t() | nil,
          :request_method => String.t() | nil,
          :request_url => String.t() | nil,
          :sid => String.t() | nil,
          :uri => String.t() | nil
        }

  def decode(value) do
    value
  end
end
