# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Heckler.Adapters.Twilio.Model.AccountCallUserDefinedMessageSubscription do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :account_sid,
    :call_sid,
    :sid,
    :date_created,
    :uri
  ]

  @type t :: %__MODULE__{
          :account_sid => String.t() | nil,
          :call_sid => String.t() | nil,
          :sid => String.t() | nil,
          :date_created => String.t() | nil,
          :uri => String.t() | nil
        }

  def decode(value) do
    value
  end
end
