# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Heckler.Adapters.Twilio.Model.AccountQueueMember do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :call_sid,
    :date_enqueued,
    :position,
    :uri,
    :wait_time,
    :queue_sid
  ]

  @type t :: %__MODULE__{
    :call_sid => String.t | nil,
    :date_enqueued => String.t | nil,
    :position => integer() | nil,
    :uri => String.t | nil,
    :wait_time => integer() | nil,
    :queue_sid => String.t | nil
  }

  def decode(value) do
    value
  end
end

