# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Heckler.Adapters.Twilio.Model.Account do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :auth_token,
    :date_created,
    :date_updated,
    :friendly_name,
    :owner_account_sid,
    :sid,
    :status,
    :subresource_uris,
    :type,
    :uri
  ]

  @type t :: %__MODULE__{
    :auth_token => String.t | nil,
    :date_created => String.t | nil,
    :date_updated => String.t | nil,
    :friendly_name => String.t | nil,
    :owner_account_sid => String.t | nil,
    :sid => String.t | nil,
    :status => Heckler.Adapters.Twilio.Model.AccountEnumStatus.t | nil,
    :subresource_uris => map() | nil,
    :type => Heckler.Adapters.Twilio.Model.AccountEnumType.t | nil,
    :uri => String.t | nil
  }

  alias Heckler.Adapters.Twilio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:status, :struct, Heckler.Adapters.Twilio.Model.AccountEnumStatus)
     |> Deserializer.deserialize(:type, :struct, Heckler.Adapters.Twilio.Model.AccountEnumType)
  end
end

