# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Heckler.Adapters.Twilio.Model.AccountAvailablePhoneNumberCountryAvailablePhoneNumberLocalCapabilities do
  @moduledoc """
  The set of Boolean properties that indicate whether a phone number can receive calls or messages.  Capabilities are: `Voice`, `SMS`, and `MMS` and each capability can be: `true` or `false`.
  """

  @derive Jason.Encoder
  defstruct [
    :mms,
    :sms,
    :voice,
    :fax
  ]

  @type t :: %__MODULE__{
    :mms => boolean() | nil,
    :sms => boolean() | nil,
    :voice => boolean() | nil,
    :fax => boolean() | nil
  }

  def decode(value) do
    value
  end
end

