# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Heckler.Adapters.Twilio.Model.AccountUsageUsageTrigger do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :account_sid,
    :api_version,
    :callback_method,
    :callback_url,
    :current_value,
    :date_created,
    :date_fired,
    :date_updated,
    :friendly_name,
    :recurring,
    :sid,
    :trigger_by,
    :trigger_value,
    :uri,
    :usage_category,
    :usage_record_uri
  ]

  @type t :: %__MODULE__{
          :account_sid => String.t() | nil,
          :api_version => String.t() | nil,
          :callback_method => String.t() | nil,
          :callback_url => String.t() | nil,
          :current_value => String.t() | nil,
          :date_created => String.t() | nil,
          :date_fired => String.t() | nil,
          :date_updated => String.t() | nil,
          :friendly_name => String.t() | nil,
          :recurring => Heckler.Adapters.Twilio.Model.UsageTriggerEnumRecurring.t() | nil,
          :sid => String.t() | nil,
          :trigger_by => Heckler.Adapters.Twilio.Model.UsageTriggerEnumTriggerField.t() | nil,
          :trigger_value => String.t() | nil,
          :uri => String.t() | nil,
          :usage_category =>
            Heckler.Adapters.Twilio.Model.UsageTriggerEnumUsageCategory.t() | nil,
          :usage_record_uri => String.t() | nil
        }

  alias Heckler.Adapters.Twilio.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :recurring,
      :struct,
      Heckler.Adapters.Twilio.Model.UsageTriggerEnumRecurring
    )
    |> Deserializer.deserialize(
      :trigger_by,
      :struct,
      Heckler.Adapters.Twilio.Model.UsageTriggerEnumTriggerField
    )
    |> Deserializer.deserialize(
      :usage_category,
      :struct,
      Heckler.Adapters.Twilio.Model.UsageTriggerEnumUsageCategory
    )
  end
end
