# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Heckler.Adapters.Twilio.Model.AccountIncomingPhoneNumberIncomingPhoneNumberAssignedAddOn do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :sid,
    :account_sid,
    :resource_sid,
    :friendly_name,
    :description,
    :configuration,
    :unique_name,
    :date_created,
    :date_updated,
    :uri,
    :subresource_uris
  ]

  @type t :: %__MODULE__{
          :sid => String.t() | nil,
          :account_sid => String.t() | nil,
          :resource_sid => String.t() | nil,
          :friendly_name => String.t() | nil,
          :description => String.t() | nil,
          :configuration => any() | nil,
          :unique_name => String.t() | nil,
          :date_created => String.t() | nil,
          :date_updated => String.t() | nil,
          :uri => String.t() | nil,
          :subresource_uris => map() | nil
        }

  def decode(value) do
    value
  end
end
