# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Heckler.Adapters.Twilio.Model.AccountValidationRequest do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :account_sid,
    :call_sid,
    :friendly_name,
    :phone_number,
    :validation_code
  ]

  @type t :: %__MODULE__{
          :account_sid => String.t() | nil,
          :call_sid => String.t() | nil,
          :friendly_name => String.t() | nil,
          :phone_number => String.t() | nil,
          :validation_code => String.t() | nil
        }

  def decode(value) do
    value
  end
end
