# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Heckler.Adapters.Twilio.Model.AccountToken do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :account_sid,
    :date_created,
    :date_updated,
    :ice_servers,
    :password,
    :ttl,
    :username
  ]

  @type t :: %__MODULE__{
          :account_sid => String.t() | nil,
          :date_created => String.t() | nil,
          :date_updated => String.t() | nil,
          :ice_servers => [Heckler.Adapters.Twilio.Model.AccountTokenIceServersInner.t()] | nil,
          :password => String.t() | nil,
          :ttl => String.t() | nil,
          :username => String.t() | nil
        }

  alias Heckler.Adapters.Twilio.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :ice_servers,
      :list,
      Heckler.Adapters.Twilio.Model.AccountTokenIceServersInner
    )
  end
end
