# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Heckler.Adapters.Twilio.Model.AccountCallRealtimeTranscription do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :sid,
    :account_sid,
    :call_sid,
    :name,
    :status,
    :date_updated,
    :uri
  ]

  @type t :: %__MODULE__{
          :sid => String.t() | nil,
          :account_sid => String.t() | nil,
          :call_sid => String.t() | nil,
          :name => String.t() | nil,
          :status => Heckler.Adapters.Twilio.Model.RealtimeTranscriptionEnumStatus.t() | nil,
          :date_updated => String.t() | nil,
          :uri => String.t() | nil
        }

  alias Heckler.Adapters.Twilio.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :status,
      :struct,
      Heckler.Adapters.Twilio.Model.RealtimeTranscriptionEnumStatus
    )
  end
end
