version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: heckler-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: heckler_dev
    ports:
      - "5432:5432"
    volumes:
      - heckler-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  heckler-postgres-data: