# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Heckler.Adapters.Twilio.Api.AssignedAddOnExtension do
  @moduledoc """
  API calls for all endpoints tagged `AssignedAddOnExtension`.
  """

  alias Heckler.Adapters.Twilio.Connection
  import Heckler.Adapters.Twilio.RequestBuilder

  @doc """
  Fetch an instance of an Extension for the Assigned Add-on.

  ### Parameters

  - `connection` (Heckler.Adapters.Twilio.Connection): Connection to server
  - `account_sid` (String.t): The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the resource to fetch.
  - `resource_sid` (String.t): The SID of the Phone Number to which the Add-on is assigned.
  - `assigned_add_on_sid` (String.t): The SID that uniquely identifies the assigned Add-on installation.
  - `sid` (String.t): The Twilio-provided string that uniquely identifies the resource to fetch.
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, Heckler.Adapters.Twilio.Model.AccountIncomingPhoneNumberIncomingPhoneNumberAssignedAddOnIncomingPhoneNumberAssignedAddOnExtension.t()}` on success
  - `{:error, Tesla.Env.t()}` on failure
  """
  @spec fetch_incoming_phone_number_assigned_add_on_extension(
          Tesla.Env.client(),
          String.t(),
          String.t(),
          String.t(),
          String.t(),
          keyword()
        ) ::
          {:ok,
           Heckler.Adapters.Twilio.Model.AccountIncomingPhoneNumberIncomingPhoneNumberAssignedAddOnIncomingPhoneNumberAssignedAddOnExtension.t()}
          | {:error, Tesla.Env.t()}
  def fetch_incoming_phone_number_assigned_add_on_extension(
        connection,
        account_sid,
        resource_sid,
        assigned_add_on_sid,
        sid,
        _opts \\ []
      ) do
    request =
      %{}
      |> method(:get)
      |> url(
        "/2010-04-01/Accounts/#{account_sid}/IncomingPhoneNumbers/#{resource_sid}/AssignedAddOns/#{assigned_add_on_sid}/Extensions/#{sid}.json"
      )
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200,
       Heckler.Adapters.Twilio.Model.AccountIncomingPhoneNumberIncomingPhoneNumberAssignedAddOnIncomingPhoneNumberAssignedAddOnExtension}
    ])
  end

  @doc """
  Retrieve a list of Extensions for the Assigned Add-on.

  ### Parameters

  - `connection` (Heckler.Adapters.Twilio.Connection): Connection to server
  - `account_sid` (String.t): The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the resources to read.
  - `resource_sid` (String.t): The SID of the Phone Number to which the Add-on is assigned.
  - `assigned_add_on_sid` (String.t): The SID that uniquely identifies the assigned Add-on installation.
  - `opts` (keyword): Optional parameters
    - `:PageSize` (integer()): How many resources to return in each list page. The default is 50, and the maximum is 1000.
    - `:Page` (integer()): The page index. This value is simply for client state.
    - `:PageToken` (String.t): The page token. This is provided by the API.

  ### Returns

  - `{:ok, Heckler.Adapters.Twilio.Model.ListIncomingPhoneNumberAssignedAddOnExtensionResponse.t()}` on success
  - `{:error, Tesla.Env.t()}` on failure
  """
  @spec list_incoming_phone_number_assigned_add_on_extension(
          Tesla.Env.client(),
          String.t(),
          String.t(),
          String.t(),
          keyword()
        ) ::
          {:ok,
           Heckler.Adapters.Twilio.Model.ListIncomingPhoneNumberAssignedAddOnExtensionResponse.t()}
          | {:error, Tesla.Env.t()}
  def list_incoming_phone_number_assigned_add_on_extension(
        connection,
        account_sid,
        resource_sid,
        assigned_add_on_sid,
        opts \\ []
      ) do
    optional_params = %{
      :PageSize => :query,
      :Page => :query,
      :PageToken => :query
    }

    request =
      %{}
      |> method(:get)
      |> url(
        "/2010-04-01/Accounts/#{account_sid}/IncomingPhoneNumbers/#{resource_sid}/AssignedAddOns/#{assigned_add_on_sid}/Extensions.json"
      )
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, Heckler.Adapters.Twilio.Model.ListIncomingPhoneNumberAssignedAddOnExtensionResponse}
    ])
  end
end
