# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Heckler.Adapters.Twilio.Api.CredentialListMapping do
  @moduledoc """
  API calls for all endpoints tagged `CredentialListMapping`.
  """

  alias Heckler.Adapters.Twilio.Connection
  import Heckler.Adapters.Twilio.RequestBuilder

  @doc """
  Create a CredentialListMapping resource for an account.

  ### Parameters

  - `connection` (Heckler.Adapters.Twilio.Connection): Connection to server
  - `account_sid` (String.t): The unique id of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this resource.
  - `domain_sid` (String.t): A 34 character string that uniquely identifies the SIP Domain for which the CredentialList resource will be mapped.
  - `credential_list_sid` (String.t): A 34 character string that uniquely identifies the CredentialList resource to map to the SIP domain.
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, Heckler.Adapters.Twilio.Model.AccountSipSipDomainSipCredentialListMapping.t()}` on success
  - `{:error, Tesla.Env.t()}` on failure
  """
  @spec create_sip_credential_list_mapping(Tesla.Env.client, String.t, String.t, String.t, keyword()) :: {:ok, Heckler.Adapters.Twilio.Model.AccountSipSipDomainSipCredentialListMapping.t()} | {:error, Tesla.Env.t()}
  def create_sip_credential_list_mapping(connection, account_sid, domain_sid, credential_list_sid, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/2010-04-01/Accounts/#{account_sid}/SIP/Domains/#{domain_sid}/CredentialListMappings.json")
      |> add_param(:form, :CredentialListSid, credential_list_sid)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, Heckler.Adapters.Twilio.Model.AccountSipSipDomainSipCredentialListMapping}
    ])
  end

  @doc """
  Delete a CredentialListMapping resource from an account.

  ### Parameters

  - `connection` (Heckler.Adapters.Twilio.Connection): Connection to server
  - `account_sid` (String.t): The unique id of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this resource.
  - `domain_sid` (String.t): A 34 character string that uniquely identifies the SIP Domain that includes the resource to delete.
  - `sid` (String.t): A 34 character string that uniquely identifies the resource to delete.
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t()}` on failure
  """
  @spec delete_sip_credential_list_mapping(Tesla.Env.client, String.t, String.t, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t()}
  def delete_sip_credential_list_mapping(connection, account_sid, domain_sid, sid, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/2010-04-01/Accounts/#{account_sid}/SIP/Domains/#{domain_sid}/CredentialListMappings/#{sid}.json")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false}
    ])
  end

  @doc """
  Fetch a single CredentialListMapping resource from an account.

  ### Parameters

  - `connection` (Heckler.Adapters.Twilio.Connection): Connection to server
  - `account_sid` (String.t): The unique id of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this resource.
  - `domain_sid` (String.t): A 34 character string that uniquely identifies the SIP Domain that includes the resource to fetch.
  - `sid` (String.t): A 34 character string that uniquely identifies the resource to fetch.
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, Heckler.Adapters.Twilio.Model.AccountSipSipDomainSipCredentialListMapping.t()}` on success
  - `{:error, Tesla.Env.t()}` on failure
  """
  @spec fetch_sip_credential_list_mapping(Tesla.Env.client, String.t, String.t, String.t, keyword()) :: {:ok, Heckler.Adapters.Twilio.Model.AccountSipSipDomainSipCredentialListMapping.t()} | {:error, Tesla.Env.t()}
  def fetch_sip_credential_list_mapping(connection, account_sid, domain_sid, sid, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/2010-04-01/Accounts/#{account_sid}/SIP/Domains/#{domain_sid}/CredentialListMappings/#{sid}.json")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, Heckler.Adapters.Twilio.Model.AccountSipSipDomainSipCredentialListMapping}
    ])
  end

  @doc """
  Read multiple CredentialListMapping resources from an account.

  ### Parameters

  - `connection` (Heckler.Adapters.Twilio.Connection): Connection to server
  - `account_sid` (String.t): The unique id of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this resource.
  - `domain_sid` (String.t): A 34 character string that uniquely identifies the SIP Domain that includes the resource to read.
  - `opts` (keyword): Optional parameters
    - `:PageSize` (integer()): How many resources to return in each list page. The default is 50, and the maximum is 1000.
    - `:Page` (integer()): The page index. This value is simply for client state.
    - `:PageToken` (String.t): The page token. This is provided by the API.

  ### Returns

  - `{:ok, Heckler.Adapters.Twilio.Model.ListSipCredentialListMappingResponse.t()}` on success
  - `{:error, Tesla.Env.t()}` on failure
  """
  @spec list_sip_credential_list_mapping(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, Heckler.Adapters.Twilio.Model.ListSipCredentialListMappingResponse.t()} | {:error, Tesla.Env.t()}
  def list_sip_credential_list_mapping(connection, account_sid, domain_sid, opts \\ []) do
    optional_params = %{
      :PageSize => :query,
      :Page => :query,
      :PageToken => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/2010-04-01/Accounts/#{account_sid}/SIP/Domains/#{domain_sid}/CredentialListMappings.json")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, Heckler.Adapters.Twilio.Model.ListSipCredentialListMappingResponse}
    ])
  end
end
