# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Heckler.Adapters.Twilio.Api.IpAccessControlList do
  @moduledoc """
  API calls for all endpoints tagged `IpAccessControlList`.
  """

  alias Heckler.Adapters.Twilio.Connection
  import Heckler.Adapters.Twilio.RequestBuilder

  @doc """
  Create a new IpAccessControlList resource

  ### Parameters

  - `connection` (Heckler.Adapters.Twilio.Connection): Connection to server
  - `account_sid` (String.t): The unique id of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this resource.
  - `friendly_name` (String.t): A human readable descriptive text that describes the IpAccessControlList, up to 255 characters long.
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, Heckler.Adapters.Twilio.Model.AccountSipSipIpAccessControlList.t()}` on success
  - `{:error, Tesla.Env.t()}` on failure
  """
  @spec create_sip_ip_access_control_list(Tesla.Env.client(), String.t(), String.t(), keyword()) ::
          {:ok, Heckler.Adapters.Twilio.Model.AccountSipSipIpAccessControlList.t()}
          | {:error, Tesla.Env.t()}
  def create_sip_ip_access_control_list(connection, account_sid, friendly_name, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/2010-04-01/Accounts/#{account_sid}/SIP/IpAccessControlLists.json")
      |> add_param(:form, :FriendlyName, friendly_name)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, Heckler.Adapters.Twilio.Model.AccountSipSipIpAccessControlList}
    ])
  end

  @doc """
  Delete an IpAccessControlList from the requested account

  ### Parameters

  - `connection` (Heckler.Adapters.Twilio.Connection): Connection to server
  - `account_sid` (String.t): The unique id of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this resource.
  - `sid` (String.t): A 34 character string that uniquely identifies the resource to delete.
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t()}` on failure
  """
  @spec delete_sip_ip_access_control_list(Tesla.Env.client(), String.t(), String.t(), keyword()) ::
          {:ok, nil} | {:error, Tesla.Env.t()}
  def delete_sip_ip_access_control_list(connection, account_sid, sid, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/2010-04-01/Accounts/#{account_sid}/SIP/IpAccessControlLists/#{sid}.json")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false}
    ])
  end

  @doc """
  Fetch a specific instance of an IpAccessControlList

  ### Parameters

  - `connection` (Heckler.Adapters.Twilio.Connection): Connection to server
  - `account_sid` (String.t): The unique id of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this resource.
  - `sid` (String.t): A 34 character string that uniquely identifies the resource to fetch.
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, Heckler.Adapters.Twilio.Model.AccountSipSipIpAccessControlList.t()}` on success
  - `{:error, Tesla.Env.t()}` on failure
  """
  @spec fetch_sip_ip_access_control_list(Tesla.Env.client(), String.t(), String.t(), keyword()) ::
          {:ok, Heckler.Adapters.Twilio.Model.AccountSipSipIpAccessControlList.t()}
          | {:error, Tesla.Env.t()}
  def fetch_sip_ip_access_control_list(connection, account_sid, sid, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/2010-04-01/Accounts/#{account_sid}/SIP/IpAccessControlLists/#{sid}.json")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, Heckler.Adapters.Twilio.Model.AccountSipSipIpAccessControlList}
    ])
  end

  @doc """
  Retrieve a list of IpAccessControlLists that belong to the account used to make the request

  ### Parameters

  - `connection` (Heckler.Adapters.Twilio.Connection): Connection to server
  - `account_sid` (String.t): The unique id of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this resource.
  - `opts` (keyword): Optional parameters
    - `:PageSize` (integer()): How many resources to return in each list page. The default is 50, and the maximum is 1000.
    - `:Page` (integer()): The page index. This value is simply for client state.
    - `:PageToken` (String.t): The page token. This is provided by the API.

  ### Returns

  - `{:ok, Heckler.Adapters.Twilio.Model.ListSipIpAccessControlListResponse.t()}` on success
  - `{:error, Tesla.Env.t()}` on failure
  """
  @spec list_sip_ip_access_control_list(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, Heckler.Adapters.Twilio.Model.ListSipIpAccessControlListResponse.t()}
          | {:error, Tesla.Env.t()}
  def list_sip_ip_access_control_list(connection, account_sid, opts \\ []) do
    optional_params = %{
      :PageSize => :query,
      :Page => :query,
      :PageToken => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/2010-04-01/Accounts/#{account_sid}/SIP/IpAccessControlLists.json")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, Heckler.Adapters.Twilio.Model.ListSipIpAccessControlListResponse}
    ])
  end

  @doc """
  Rename an IpAccessControlList

  ### Parameters

  - `connection` (Heckler.Adapters.Twilio.Connection): Connection to server
  - `account_sid` (String.t): The unique id of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this resource.
  - `sid` (String.t): A 34 character string that uniquely identifies the resource to udpate.
  - `friendly_name` (String.t): A human readable descriptive text, up to 255 characters long.
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, Heckler.Adapters.Twilio.Model.AccountSipSipIpAccessControlList.t()}` on success
  - `{:error, Tesla.Env.t()}` on failure
  """
  @spec update_sip_ip_access_control_list(
          Tesla.Env.client(),
          String.t(),
          String.t(),
          String.t(),
          keyword()
        ) ::
          {:ok, Heckler.Adapters.Twilio.Model.AccountSipSipIpAccessControlList.t()}
          | {:error, Tesla.Env.t()}
  def update_sip_ip_access_control_list(connection, account_sid, sid, friendly_name, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/2010-04-01/Accounts/#{account_sid}/SIP/IpAccessControlLists/#{sid}.json")
      |> add_param(:form, :FriendlyName, friendly_name)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, Heckler.Adapters.Twilio.Model.AccountSipSipIpAccessControlList}
    ])
  end
end
