# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Heckler.Adapters.Twilio.Api.IpAccessControlListMapping do
  @moduledoc """
  API calls for all endpoints tagged `IpAccessControlListMapping`.
  """

  alias Heckler.Adapters.Twilio.Connection
  import Heckler.Adapters.Twilio.RequestBuilder

  @doc """
  Create a new IpAccessControlListMapping resource.

  ### Parameters

  - `connection` (Heckler.Adapters.Twilio.Connection): Connection to server
  - `account_sid` (String.t): The unique id of the Account that is responsible for this resource.
  - `domain_sid` (String.t): A 34 character string that uniquely identifies the SIP domain.
  - `ip_access_control_list_sid` (String.t): The unique id of the IP access control list to map to the SIP domain.
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, Heckler.Adapters.Twilio.Model.AccountSipSipDomainSipIpAccessControlListMapping.t()}` on success
  - `{:error, Tesla.Env.t()}` on failure
  """
  @spec create_sip_ip_access_control_list_mapping(Tesla.Env.client, String.t, String.t, String.t, keyword()) :: {:ok, Heckler.Adapters.Twilio.Model.AccountSipSipDomainSipIpAccessControlListMapping.t()} | {:error, Tesla.Env.t()}
  def create_sip_ip_access_control_list_mapping(connection, account_sid, domain_sid, ip_access_control_list_sid, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/2010-04-01/Accounts/#{account_sid}/SIP/Domains/#{domain_sid}/IpAccessControlListMappings.json")
      |> add_param(:form, :IpAccessControlListSid, ip_access_control_list_sid)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, Heckler.Adapters.Twilio.Model.AccountSipSipDomainSipIpAccessControlListMapping}
    ])
  end

  @doc """
  Delete an IpAccessControlListMapping resource.

  ### Parameters

  - `connection` (Heckler.Adapters.Twilio.Connection): Connection to server
  - `account_sid` (String.t): The unique id of the Account that is responsible for this resource.
  - `domain_sid` (String.t): A 34 character string that uniquely identifies the SIP domain.
  - `sid` (String.t): A 34 character string that uniquely identifies the resource to delete.
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t()}` on failure
  """
  @spec delete_sip_ip_access_control_list_mapping(Tesla.Env.client, String.t, String.t, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t()}
  def delete_sip_ip_access_control_list_mapping(connection, account_sid, domain_sid, sid, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/2010-04-01/Accounts/#{account_sid}/SIP/Domains/#{domain_sid}/IpAccessControlListMappings/#{sid}.json")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false}
    ])
  end

  @doc """
  Fetch an IpAccessControlListMapping resource.

  ### Parameters

  - `connection` (Heckler.Adapters.Twilio.Connection): Connection to server
  - `account_sid` (String.t): The unique id of the Account that is responsible for this resource.
  - `domain_sid` (String.t): A 34 character string that uniquely identifies the SIP domain.
  - `sid` (String.t): A 34 character string that uniquely identifies the resource to fetch.
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, Heckler.Adapters.Twilio.Model.AccountSipSipDomainSipIpAccessControlListMapping.t()}` on success
  - `{:error, Tesla.Env.t()}` on failure
  """
  @spec fetch_sip_ip_access_control_list_mapping(Tesla.Env.client, String.t, String.t, String.t, keyword()) :: {:ok, Heckler.Adapters.Twilio.Model.AccountSipSipDomainSipIpAccessControlListMapping.t()} | {:error, Tesla.Env.t()}
  def fetch_sip_ip_access_control_list_mapping(connection, account_sid, domain_sid, sid, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/2010-04-01/Accounts/#{account_sid}/SIP/Domains/#{domain_sid}/IpAccessControlListMappings/#{sid}.json")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, Heckler.Adapters.Twilio.Model.AccountSipSipDomainSipIpAccessControlListMapping}
    ])
  end

  @doc """
  Retrieve a list of IpAccessControlListMapping resources.

  ### Parameters

  - `connection` (Heckler.Adapters.Twilio.Connection): Connection to server
  - `account_sid` (String.t): The unique id of the Account that is responsible for this resource.
  - `domain_sid` (String.t): A 34 character string that uniquely identifies the SIP domain.
  - `opts` (keyword): Optional parameters
    - `:PageSize` (integer()): How many resources to return in each list page. The default is 50, and the maximum is 1000.
    - `:Page` (integer()): The page index. This value is simply for client state.
    - `:PageToken` (String.t): The page token. This is provided by the API.

  ### Returns

  - `{:ok, Heckler.Adapters.Twilio.Model.ListSipIpAccessControlListMappingResponse.t()}` on success
  - `{:error, Tesla.Env.t()}` on failure
  """
  @spec list_sip_ip_access_control_list_mapping(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, Heckler.Adapters.Twilio.Model.ListSipIpAccessControlListMappingResponse.t()} | {:error, Tesla.Env.t()}
  def list_sip_ip_access_control_list_mapping(connection, account_sid, domain_sid, opts \\ []) do
    optional_params = %{
      :PageSize => :query,
      :Page => :query,
      :PageToken => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/2010-04-01/Accounts/#{account_sid}/SIP/Domains/#{domain_sid}/IpAccessControlListMappings.json")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, Heckler.Adapters.Twilio.Model.ListSipIpAccessControlListMappingResponse}
    ])
  end
end
