# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Heckler.Adapters.Twilio.Api.MachineToMachine do
  @moduledoc """
  API calls for all endpoints tagged `MachineToMachine`.
  """

  alias Heckler.Adapters.Twilio.Connection
  import Heckler.Adapters.Twilio.RequestBuilder

  @doc """
  

  ### Parameters

  - `connection` (Heckler.Adapters.Twilio.Connection): Connection to server
  - `account_sid` (String.t): The SID of the [Account](https://www.twilio.com/docs/iam/api/account) requesting the AvailablePhoneNumber resources.
  - `country_code` (String.t): The [ISO-3166-1](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country code of the country from which to read phone numbers.
  - `opts` (keyword): Optional parameters
    - `:AreaCode` (integer()): The area code of the phone numbers to read. Applies to only phone numbers in the US and Canada.
    - `:Contains` (String.t): The pattern on which to match phone numbers. Valid characters are `*`, `0-9`, `a-z`, and `A-Z`. The `*` character matches any single digit. For examples, see [Example 2](https://www.twilio.com/docs/phone-numbers/api/availablephonenumber-resource#local-get-basic-example-2) and [Example 3](https://www.twilio.com/docs/phone-numbers/api/availablephonenumber-resource#local-get-basic-example-3). If specified, this value must have at least two characters.
    - `:SmsEnabled` (boolean()): Whether the phone numbers can receive text messages. Can be: `true` or `false`.
    - `:MmsEnabled` (boolean()): Whether the phone numbers can receive MMS messages. Can be: `true` or `false`.
    - `:VoiceEnabled` (boolean()): Whether the phone numbers can receive calls. Can be: `true` or `false`.
    - `:ExcludeAllAddressRequired` (boolean()): Whether to exclude phone numbers that require an [Address](https://www.twilio.com/docs/usage/api/address). Can be: `true` or `false` and the default is `false`.
    - `:ExcludeLocalAddressRequired` (boolean()): Whether to exclude phone numbers that require a local [Address](https://www.twilio.com/docs/usage/api/address). Can be: `true` or `false` and the default is `false`.
    - `:ExcludeForeignAddressRequired` (boolean()): Whether to exclude phone numbers that require a foreign [Address](https://www.twilio.com/docs/usage/api/address). Can be: `true` or `false` and the default is `false`.
    - `:Beta` (boolean()): Whether to read phone numbers that are new to the Twilio platform. Can be: `true` or `false` and the default is `true`.
    - `:NearNumber` (String.t): Given a phone number, find a geographically close number within `distance` miles. Distance defaults to 25 miles. Applies to only phone numbers in the US and Canada.
    - `:NearLatLong` (String.t): Given a latitude/longitude pair `lat,long` find geographically close numbers within `distance` miles. Applies to only phone numbers in the US and Canada.
    - `:Distance` (integer()): The search radius, in miles, for a `near_` query.  Can be up to `500` and the default is `25`. Applies to only phone numbers in the US and Canada.
    - `:InPostalCode` (String.t): Limit results to a particular postal code. Given a phone number, search within the same postal code as that number. Applies to only phone numbers in the US and Canada.
    - `:InRegion` (String.t): Limit results to a particular region, state, or province. Given a phone number, search within the same region as that number. Applies to only phone numbers in the US and Canada.
    - `:InRateCenter` (String.t): Limit results to a specific rate center, or given a phone number search within the same rate center as that number. Requires `in_lata` to be set as well. Applies to only phone numbers in the US and Canada.
    - `:InLata` (String.t): Limit results to a specific local access and transport area ([LATA](https://en.wikipedia.org/wiki/Local_access_and_transport_area)). Given a phone number, search within the same [LATA](https://en.wikipedia.org/wiki/Local_access_and_transport_area) as that number. Applies to only phone numbers in the US and Canada.
    - `:InLocality` (String.t): Limit results to a particular locality or city. Given a phone number, search within the same Locality as that number.
    - `:FaxEnabled` (boolean()): Whether the phone numbers can receive faxes. Can be: `true` or `false`.
    - `:PageSize` (integer()): How many resources to return in each list page. The default is 50, and the maximum is 1000.
    - `:Page` (integer()): The page index. This value is simply for client state.
    - `:PageToken` (String.t): The page token. This is provided by the API.

  ### Returns

  - `{:ok, Heckler.Adapters.Twilio.Model.ListAvailablePhoneNumberMachineToMachineResponse.t()}` on success
  - `{:error, Tesla.Env.t()}` on failure
  """
  @spec list_available_phone_number_machine_to_machine(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, Heckler.Adapters.Twilio.Model.ListAvailablePhoneNumberMachineToMachineResponse.t()} | {:error, Tesla.Env.t()}
  def list_available_phone_number_machine_to_machine(connection, account_sid, country_code, opts \\ []) do
    optional_params = %{
      :AreaCode => :query,
      :Contains => :query,
      :SmsEnabled => :query,
      :MmsEnabled => :query,
      :VoiceEnabled => :query,
      :ExcludeAllAddressRequired => :query,
      :ExcludeLocalAddressRequired => :query,
      :ExcludeForeignAddressRequired => :query,
      :Beta => :query,
      :NearNumber => :query,
      :NearLatLong => :query,
      :Distance => :query,
      :InPostalCode => :query,
      :InRegion => :query,
      :InRateCenter => :query,
      :InLata => :query,
      :InLocality => :query,
      :FaxEnabled => :query,
      :PageSize => :query,
      :Page => :query,
      :PageToken => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/2010-04-01/Accounts/#{account_sid}/AvailablePhoneNumbers/#{country_code}/MachineToMachine.json")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, Heckler.Adapters.Twilio.Model.ListAvailablePhoneNumberMachineToMachineResponse}
    ])
  end
end
