# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Heckler.Adapters.Twilio.Api.NewSigningKey do
  @moduledoc """
  API calls for all endpoints tagged `NewSigningKey`.
  """

  alias Heckler.Adapters.Twilio.Connection
  import Heckler.Adapters.Twilio.RequestBuilder

  @doc """
  Create a new Signing Key for the account making the request.

  ### Parameters

  - `connection` (Heckler.Adapters.Twilio.Connection): Connection to server
  - `account_sid` (String.t): The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that will be responsible for the new Key resource.
  - `opts` (keyword): Optional parameters
    - `:FriendlyName` (String.t): A descriptive string that you create to describe the resource. It can be up to 64 characters long.

  ### Returns

  - `{:ok, Heckler.Adapters.Twilio.Model.AccountNewSigningKey.t()}` on success
  - `{:error, Tesla.Env.t()}` on failure
  """
  @spec create_new_signing_key(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, Heckler.Adapters.Twilio.Model.AccountNewSigningKey.t()} | {:error, Tesla.Env.t()}
  def create_new_signing_key(connection, account_sid, opts \\ []) do
    optional_params = %{
      :FriendlyName => :form
    }

    request =
      %{}
      |> method(:post)
      |> url("/2010-04-01/Accounts/#{account_sid}/SigningKeys.json")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, Heckler.Adapters.Twilio.Model.AccountNewSigningKey}
    ])
  end
end
