# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Heckler.Adapters.Twilio.Api.Payment do
  @moduledoc """
  API calls for all endpoints tagged `Payment`.
  """

  alias Heckler.Adapters.Twilio.Connection
  import Heckler.Adapters.Twilio.RequestBuilder

  @doc """
  create an instance of payments. This will start a new payments session

  ### Parameters

  - `connection` (Heckler.Adapters.Twilio.Connection): Connection to server
  - `account_sid` (String.t): The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that will create the resource.
  - `call_sid` (String.t): The SID of the call that will create the resource. Call leg associated with this sid is expected to provide payment information thru DTMF.
  - `idempotency_key` (String.t): A unique token that will be used to ensure that multiple API calls with the same information do not result in multiple transactions. This should be a unique string value per API call and can be a randomly generated.
  - `status_callback` (String.t): Provide an absolute or relative URL to receive status updates regarding your Pay session. Read more about the [expected StatusCallback values](https://www.twilio.com/docs/voice/api/payment-resource#statuscallback)
  - `opts` (keyword): Optional parameters
    - `:BankAccountType` (Heckler.Adapters.Twilio.Model.PaymentsEnumBankAccountType.t): 
    - `:ChargeAmount` (float()): A positive decimal value less than 1,000,000 to charge against the credit card or bank account. Default currency can be overwritten with `currency` field. Leave blank or set to 0 to tokenize.
    - `:Currency` (String.t): The currency of the `charge_amount`, formatted as [ISO 4127](http://www.iso.org/iso/home/standards/currency_codes.htm) format. The default value is `USD` and all values allowed from the Pay Connector are accepted.
    - `:Description` (String.t): The description can be used to provide more details regarding the transaction. This information is submitted along with the payment details to the Payment Connector which are then posted on the transactions.
    - `:Input` (String.t): A list of inputs that should be accepted. Currently only `dtmf` is supported. All digits captured during a pay session are redacted from the logs.
    - `:MinPostalCodeLength` (integer()): A positive integer that is used to validate the length of the `PostalCode` inputted by the user. User must enter this many digits.
    - `:Parameter` (any()): A single-level JSON object used to pass custom parameters to payment processors. (Required for ACH payments). The information that has to be included here depends on the <Pay> Connector. [Read more](https://www.twilio.com/console/voice/pay-connectors).
    - `:PaymentConnector` (String.t): This is the unique name corresponding to the Pay Connector installed in the Twilio Add-ons. Learn more about [<Pay> Connectors](https://www.twilio.com/console/voice/pay-connectors). The default value is `Default`.
    - `:PaymentMethod` (Heckler.Adapters.Twilio.Model.PaymentsEnumPaymentMethod.t): 
    - `:PostalCode` (boolean()): Indicates whether the credit card postal code (zip code) is a required piece of payment information that must be provided by the caller. The default is `true`.
    - `:SecurityCode` (boolean()): Indicates whether the credit card security code is a required piece of payment information that must be provided by the caller. The default is `true`.
    - `:Timeout` (integer()): The number of seconds that <Pay> should wait for the caller to press a digit between each subsequent digit, after the first one, before moving on to validate the digits captured. The default is `5`, maximum is `600`.
    - `:TokenType` (Heckler.Adapters.Twilio.Model.PaymentsEnumTokenType.t): 
    - `:ValidCardTypes` (String.t): Credit card types separated by space that Pay should accept. The default value is `visa mastercard amex`

  ### Returns

  - `{:ok, Heckler.Adapters.Twilio.Model.AccountCallPayments.t()}` on success
  - `{:error, Tesla.Env.t()}` on failure
  """
  @spec create_payments(
          Tesla.Env.client(),
          String.t(),
          String.t(),
          String.t(),
          String.t(),
          keyword()
        ) ::
          {:ok, Heckler.Adapters.Twilio.Model.AccountCallPayments.t()} | {:error, Tesla.Env.t()}
  def create_payments(
        connection,
        account_sid,
        call_sid,
        idempotency_key,
        status_callback,
        opts \\ []
      ) do
    optional_params = %{
      :BankAccountType => :form,
      :ChargeAmount => :form,
      :Currency => :form,
      :Description => :form,
      :Input => :form,
      :MinPostalCodeLength => :form,
      :Parameter => :form,
      :PaymentConnector => :form,
      :PaymentMethod => :form,
      :PostalCode => :form,
      :SecurityCode => :form,
      :Timeout => :form,
      :TokenType => :form,
      :ValidCardTypes => :form
    }

    request =
      %{}
      |> method(:post)
      |> url("/2010-04-01/Accounts/#{account_sid}/Calls/#{call_sid}/Payments.json")
      |> add_param(:form, :IdempotencyKey, idempotency_key)
      |> add_param(:form, :StatusCallback, status_callback)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, Heckler.Adapters.Twilio.Model.AccountCallPayments}
    ])
  end

  @doc """
  update an instance of payments with different phases of payment flows.

  ### Parameters

  - `connection` (Heckler.Adapters.Twilio.Connection): Connection to server
  - `account_sid` (String.t): The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that will update the resource.
  - `call_sid` (String.t): The SID of the call that will update the resource. This should be the same call sid that was used to create payments resource.
  - `sid` (String.t): The SID of Payments session that needs to be updated.
  - `idempotency_key` (String.t): A unique token that will be used to ensure that multiple API calls with the same information do not result in multiple transactions. This should be a unique string value per API call and can be a randomly generated.
  - `status_callback` (String.t): Provide an absolute or relative URL to receive status updates regarding your Pay session. Read more about the [Update](https://www.twilio.com/docs/voice/api/payment-resource#statuscallback-update) and [Complete/Cancel](https://www.twilio.com/docs/voice/api/payment-resource#statuscallback-cancelcomplete) POST requests.
  - `opts` (keyword): Optional parameters
    - `:Capture` (Heckler.Adapters.Twilio.Model.PaymentsEnumCapture.t): 
    - `:Status` (Heckler.Adapters.Twilio.Model.PaymentsEnumStatus.t): 

  ### Returns

  - `{:ok, Heckler.Adapters.Twilio.Model.AccountCallPayments.t()}` on success
  - `{:error, Tesla.Env.t()}` on failure
  """
  @spec update_payments(
          Tesla.Env.client(),
          String.t(),
          String.t(),
          String.t(),
          String.t(),
          String.t(),
          keyword()
        ) ::
          {:ok, Heckler.Adapters.Twilio.Model.AccountCallPayments.t()} | {:error, Tesla.Env.t()}
  def update_payments(
        connection,
        account_sid,
        call_sid,
        sid,
        idempotency_key,
        status_callback,
        opts \\ []
      ) do
    optional_params = %{
      :Capture => :form,
      :Status => :form
    }

    request =
      %{}
      |> method(:post)
      |> url("/2010-04-01/Accounts/#{account_sid}/Calls/#{call_sid}/Payments/#{sid}.json")
      |> add_param(:form, :IdempotencyKey, idempotency_key)
      |> add_param(:form, :StatusCallback, status_callback)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {202, Heckler.Adapters.Twilio.Model.AccountCallPayments}
    ])
  end
end
