# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Heckler.Adapters.Twilio.Api.Token do
  @moduledoc """
  API calls for all endpoints tagged `Token`.
  """

  alias Heckler.Adapters.Twilio.Connection
  import Heckler.Adapters.Twilio.RequestBuilder

  @doc """
  Create a new token for ICE servers

  ### Parameters

  - `connection` (Heckler.Adapters.Twilio.Connection): Connection to server
  - `account_sid` (String.t): The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that will create the resource.
  - `opts` (keyword): Optional parameters
    - `:Ttl` (integer()): The duration in seconds for which the generated credentials are valid. The default value is 86400 (24 hours).

  ### Returns

  - `{:ok, Heckler.Adapters.Twilio.Model.AccountToken.t()}` on success
  - `{:error, Tesla.Env.t()}` on failure
  """
  @spec create_token(Tesla.Env.client, String.t, keyword()) :: {:ok, Heckler.Adapters.Twilio.Model.AccountToken.t()} | {:error, Tesla.Env.t()}
  def create_token(connection, account_sid, opts \\ []) do
    optional_params = %{
      :Ttl => :form
    }

    request =
      %{}
      |> method(:post)
      |> url("/2010-04-01/Accounts/#{account_sid}/Tokens.json")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, Heckler.Adapters.Twilio.Model.AccountToken}
    ])
  end
end
