# NOTE: This file is auto generated by OpenAPI Generator 7.10.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Heckler.Adapters.Twilio.Api.UserDefinedMessage do
  @moduledoc """
  API calls for all endpoints tagged `UserDefinedMessage`.
  """

  alias Heckler.Adapters.Twilio.Connection
  import Heckler.Adapters.Twilio.RequestBuilder

  @doc """
  Create a new User Defined Message for the given Call SID.

  ### Parameters

  - `connection` (Heckler.Adapters.Twilio.Connection): Connection to server
  - `account_sid` (String.t): The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created User Defined Message.
  - `call_sid` (String.t): The SID of the [Call](https://www.twilio.com/docs/voice/api/call-resource) the User Defined Message is associated with.
  - `content` (String.t): The User Defined Message in the form of URL-encoded JSON string.
  - `opts` (keyword): Optional parameters
    - `:IdempotencyKey` (String.t): A unique string value to identify API call. This should be a unique string value per API call and can be a randomly generated.

  ### Returns

  - `{:ok, Heckler.Adapters.Twilio.Model.AccountCallUserDefinedMessage.t()}` on success
  - `{:error, Tesla.Env.t()}` on failure
  """
  @spec create_user_defined_message(Tesla.Env.client, String.t, String.t, String.t, keyword()) :: {:ok, Heckler.Adapters.Twilio.Model.AccountCallUserDefinedMessage.t()} | {:error, Tesla.Env.t()}
  def create_user_defined_message(connection, account_sid, call_sid, content, opts \\ []) do
    optional_params = %{
      :IdempotencyKey => :form
    }

    request =
      %{}
      |> method(:post)
      |> url("/2010-04-01/Accounts/#{account_sid}/Calls/#{call_sid}/UserDefinedMessages.json")
      |> add_param(:form, :Content, content)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, Heckler.Adapters.Twilio.Model.AccountCallUserDefinedMessage}
    ])
  end
end
